[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  topics = ["zigbee2mqtt/+"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "zigbee2mqtt/+"
    tags  = "_/device"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "zigbee"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "humidity"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "battery"
      type = "float"
      optional = true

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "linkquality"
      type = "float"
      optional = true

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "zigbee"
  skip_database_creation = false
